### ISSUE TITLE
эм

### ISSUE THREAD

**Issue by SavokBS** [tailsjs/NotSoTsunami#1]
я запустил мир и меня смыло цунами и унесло в дом моргенштерна и потом меня изнасиловал слава беброу а потом пришла клава кока и у меня пошла кровь из ушей от ее песен но потом из ее тела вылез филипп киркоров и мы поехали в киев а потом на нас упал сармат и зеленка начал танцевать опа гангам стайл а байден прилетел на химарсе а начал петь песни кани иста, ну а так дп норм.

**Comment by tailsjs** [comment]
здравствуйте мы пофиксим

**Comment by tailsjs** [comment]
здравствуйте баг пофиксили надо прожать 17 кнопок на инвокере в шутере дота 2

**Comment by SavokBS** [comment]
ещё баг: когда ты заходишь в Майн тебя бросает в амонгус и красный предатель снимает свои сусси штанишки и достает свой большой огромный сладкий зенитное орудие 7,5 cm Flak L/60 с и потом там плохо пахнет

**Comment by tailsjs** [comment]
здравствуйте попробуйте стать сыном мияги тестерам помогло

**Comment by SavokBS** [comment]
идите на**************************************************************************************************************************************************************************************************************хуй

**Comment by tailsjs** [comment]
здравствуйте вам уже не помочь
